---
imagebuilder: "https://downloads.openwrt.org/releases/19.07.7/targets/ath79/generic/openwrt-imagebuilder-19.07.7-ath79-generic.Linux-x86_64.tar.xz"
feed_version: "19.07"
override_target: "ubnt_nanostation-m"

int_port: eth1

wireless_devices:
  - name: 11g_standard
    hwmode: 11g
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan2
