---
override_target: "ubnt_bullet-m-ar7241"
target: ath79/generic

int_port: eth0

low_mem: true

wireless_devices:
  - name: 11g_standard
    hwmode: 11g
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan2
    antenna_gain: 8
