---
imagebuilder: "https://downloads.openwrt.org/releases/21.02-SNAPSHOT/targets/ath79/generic/openwrt-imagebuilder-21.02-SNAPSHOT-ath79-generic.Linux-x86_64.tar.xz"
feed_version: "1.2.0-snapshot"
override_target: "ubnt_nanostation-m"

int_port: eth1

# low-mem hack
device_disabled_services__to_merge:
  - "uhttpd"

wireless_devices:
  - name: 11a_standard
    hwmode: 11a
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan5

poe_ports:
  - name: PoE Passthrough
    gpio_pin: 8
    value: 0

