---
imagebuilder: "https://downloads.openwrt.org/releases/21.02-SNAPSHOT/targets/ramips/mt7621/openwrt-imagebuilder-21.02-SNAPSHOT-ramips-mt7621.Linux-x86_64.tar.xz"
feed_version: "1.2.0-snapshot"
imagebuilder_disable_signature_check: true

# ToDo: disable falter packages temporarily
model__packages__to_merge:
  - "-luci-mod-falter"
  - "-falter-berlin-fix-luci"
  - "-luci-app-falter-owm"
  - "-luci-app-falter-owm-ant"
  - "-luci-app-falter-owm-cmd"
  - "-luci-app-falter-owm-gui"

dsa_ports:
  - eth0
  - eth1
  - eth2
  - eth3
  - eth4
  - eth5

poe_ports:
  - name: PoE Power Port0
    gpio_pin: 400
    value: 0
  - name: PoE Power Port1
    gpio_pin: 401
    value: 0
  - name: PoE Power Port2
    gpio_pin: 402
    value: 0
  - name: PoE Power Port3
    gpio_pin: 403
    value: 0
  - name: PoE Power Port4
    gpio_pin: 404
    value: 0
