---
imagebuilder: "~/git/openwrt/bin/targets/ipq40xx/mikrotik/openwrt-imagebuilder-ipq40xx-mikrotik.Linux-x86_64.tar.xz"
#feed_version: "19.07"
#instr_set: "arm_cortex-a7_neon-vfpv4"

# Somehow this doesnt work properly anymore
#switch_disable_vlan: true

switch_ports: 6
switch_int_port: 0
switch_ignore_ports: [1,2,3,4]

int_port: eth0

wireless_devices:
  - name: 11a_standard
    hwmode: 11a
    path: platform/soc/a800000.wifi
    ifname_hint: wlan5
