---
ipv6_prefix: "2001:bf7:750:4e00::/56"

# Sonnenblume got following prefixes:
# Router: 10.31.151.0/26
# --MGMT: 10.31.151.0/27
# --MESH: 10.31.151.32/27
# --DHCP: 10.31.150.0/24

networks:
  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.150.0/24
    ipv6_subprefix: 0
    assignments:
      b90gruene-core: 1

  - vid: 50
    name: prdhcp
    role: ext
    untagged: true

  - vid: 42
    role: mgmt
    prefix: 10.31.151.0/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      b90gruene-core: 1
