---
ipv6_prefix: "2001:bf7:830:9800::/56"


# Zwingli got 10.31.115.0/24

networks:
  - vid: 42
    role: mgmt
    prefix: 10.31.115.0/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      zwingli-core-neu: 1
      zwingli-switch: 2
# af60-lr
      zwingli-sama: 3
      zwingli-rhnk: 4
      zwingli-agym: 5
# 5ghz sectors
      zwingli-nord-5ghz-neu: 20

  - vid: 40
    role: dhcp
    prefix: 10.31.115.128/25
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      zwingli-core-neu: 1


# 10.31.115.32/28 Mesh Prefix (16)
  - vid: 10
    role: mesh
    name: mesh_nord
    prefix: 10.31.115.32/32
    ipv6_subprefix: -1
  - vid: 11
    role: mesh
    name: mesh_ost
    prefix: 10.31.115.33/32
    ipv6_subprefix: -2
  - vid: 12
    role: mesh
    name: mesh_sued
    prefix: 10.31.115.34/32
    ipv6_subprefix: -3
  - vid: 13
    role: mesh
    name: mesh_west
    prefix: 10.31.115.35/32
    ipv6_subprefix: -4
  - vid: 14
    role: mesh
    name: mesh_sama
    prefix: 10.31.115.36/32
    ipv6_subprefix: -5
    mesh_metric: 128
    ptp: true
  - vid: 15
    role: mesh
    name: mesh_rhnk
    prefix: 10.31.115.37/32
    ipv6_subprefix: -6
    mesh_metric: 128
    ptp: true
  - vid: 16
    role: mesh
    name: mesh_agym
    prefix: 10.31.115.38/32
    ipv6_subprefix: -7
    mesh_metric: 128
    ptp: true

# Prelimary Switchports:
# 17: Mesh Sama AF60-LR
# 18: Mesh RHNK AF60-LR
# 19: Mesh Agym AF60-LR
# 20: Mesh Nord 5GHz (Rocket)
# 21..23 ?
# 25: Core Router
# 26: DHCP Network Untagged
