---
ipv6_prefix: "2001:bf7:860::/56"

# Mesh: 10.31.83.60/30
networks:
  - vid: 10
    role: mesh
    name: mesh_sama
    prefix: 10.31.83.60/32
    ipv6_subprefix: -1

  - vid: 10
    role: mesh
    name: mesh_ost
    prefix: 10.31.83.61/32
    ipv6_subprefix: -2

  - vid: 42
    role: mgmt
    prefix: 10.31.83.112/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      magda-core: 1
      magda-switch: 2
      magda-sama: 3
      magda-ost-5ghz: 4
      magda-ap1: 5
      magda-ap2: 6
      magda-ap3: 7

  - vid: 40
    role: dhcp
    prefix: 10.31.83.192/26
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      magda-core: 1

location__channel_assignments_11a_standard__to_merge:
  magda-ap1: 36-20-10
  magda-ap2: 40-20-10
  magda-ap3: 44-20-10

# channel-bandwith-txpower in dbm

# ap1: hof
# ap2: kirche
# ap3: knast
#
