---
ipv6_prefix: "2001:bf7:750:3700::/56"

networks:
  - vid: 42
    role: mgmt
    prefix: 10.31.104.128/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      simeon-core: 1
      simeon-poe-switch: 2
      simeon-mgh: 3
      simeon-nord: 4
      simeon-emma: 5
      simeon-rhx: 6

  - vid: 40
    role: dhcp
    prefix: 10.31.104.0/25
    ipv6_subprefix: 0
    untagged: true
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      simeon-core: 1

  - vid: 10
    role: mesh
    name: mesh_mgh
    prefix: 10.31.51.136/32
    ipv6_subprefix: -1

  - vid: 11
    role: mesh
    name: mesh_nord
    prefix: 10.31.51.137/32
    ipv6_subprefix: -2

  - vid: 12
    role: mesh
    name: mesh_emma
    prefix: 10.31.51.138/32
    ipv6_subprefix: -3

  - vid: 13
    role: mesh
    name: mesh_rhx
    prefix: 10.31.51.139/32
    ipv6_subprefix: -4
