---


collectd_snmp_profiles:
  airos_8:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0
    rf_freq:
      Type: frequency
      TypeInstance: "Frequency (MHz)"
      Table: false
      Values: .1.3.6.1.4.1.41112.1.4.1.1.4.1
    rf_sta_signal:
      Type: signal_power
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.3.1
    rf_sta_cinr:
      Type: snr
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.16.1
    rf_sta_rx_capacity:
      Type: bitrate
      Table: true
      TypeInstancePrefix: "rx "
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Scale: 1000
      Values: .1.3.6.1.4.1.41112.1.4.7.1.18.1
    rf_sta_tx_capacity:
      Type: bitrate
      Table: true
      TypeInstancePrefix: "tx "
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Scale: 1000
      Values: .1.3.6.1.4.1.41112.1.4.7.1.17.1

  airos_6:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0
    rf_freq:
      Type: frequency
      TypeInstance: "Frequency (MHz)"
      Table: false
      Values: .1.3.6.1.4.1.41112.1.4.1.1.4.1
    rf_sta_signal:
      Type: signal_power
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.3.1
    rf_sta_noise:
      Type: signal_noise
      Table: true
      TypeInstancePrefix: "Noise Floor (dBm) "
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.4.1
    rf_sta_ccq:
      Type: signal_quality
      Table: true
      TypeInstancePrefix: "CCQ (%)  "
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.6.1
    rf_sta_rx_capacity:
      Type: bitrate
      Table: true
      TypeInstancePrefix: "rx "
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Scale: 1000
      Values: .1.3.6.1.4.1.41112.1.4.7.1.11.1
    rf_sta_tx_capacity:
      Type: bitrate
      Table: true
      TypeInstancePrefix: "tx "
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Scale: 1000
      Values: .1.3.6.1.4.1.41112.1.4.7.1.12.1
 
  # For PtMP APs we should define another profile which provides rf info per station
  mikrotik_60g:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0
    rf_freq:
      Type: frequency
      TypeInstance: "Frequency (MHz)"
      Table: false
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.6.1
    rf_mcs:
      Type: node_tx_rate
      TypeInstance: "MCS Level"
      Table: false
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.7.1
    rf_quality:
      Type: signal_quality
      TypeInstance: "Percent"
      Table: false
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.8.1
    rf_tx_sector:
      Type: gauge
      TypeInstance: "TX Sector"
      Table: false
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.9.1
    rf_rssi:
      Type: signal_power
      TypeInstance: "RSSI (dBm)"
      Table: false
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.12.1
    rf_phy_rate:
      Type: bitrate
      TypeInstance: "TX Bitrate"
      Scale: 1000
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.13.1
 
