---
ipv6_prefix: "2001:bf7:810:1000::/56"

networks:
  - vid: 10
    role: mesh
    name: mesh_rhxb
    prefix: 10.31.208.37/32
    ipv6_subprefix: -1

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.111.5.0/24
    ipv6_subprefix: 0
    assignments:
      manstein10-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.36.208.0/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      manstein10-core: 1
      manstein10-poe-switch-1: 2
      manstein10-poe-switch-2: 3
      # airos - bbb
      manstein10-m5-rhxb: 4
      # airos - clients
      manstein10-m5-loco-s5: 5
      manstein10-m5-w5: 6
      # openwrt clients
      manstein10-m2-s: 7
      manstein10-m2-w: 8
