---
ipv6_prefix: "2001:bf7:750:3600::/56"

networks:
  - vid: 10
    role: mesh
    name: mesh_emma
    prefix: 10.31.18.130/32
    ipv6_subprefix: -1
    mesh_metric_lqm: ['default 0.2']
    mesh_metric: 2048

  - vid: 11
    role: mesh
    name: mesh_simon
    prefix: 10.31.19.8/32
    ipv6_subprefix: -2
    mesh_metric: 256

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    untagged: true
    prefix: 10.31.102.128/25
    ipv6_subprefix: 0
    assignments:
      koepi-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.102.0/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      koepi-core: 1

location__channel_assignments_11a_standard__to_merge:
  koepi-core: 36-20

location__channel_assignments_11g_standard__to_merge:
  koepi-core: 1-20

