---
ipv6_prefix: "2001:bf7:830:9d00::/56"

# mesh: 10.31.109.64/30
networks:
  - vid: 10
    role: mesh
    name: mesh_sama
    prefix: 10.31.109.64/32
    ipv6_subprefix: -1

  - vid: 11
    role: mesh
    name: mesh_rhnk
    prefix: 10.31.109.65/32
    ipv6_subprefix: -2

  - vid: 42
    role: mgmt
    prefix: 10.31.119.128/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      rigaer78-core: 1
      rigaer78-poe: 2 # reserved
      rigaer78-sama: 3
      rigaer78-zwingli: 4
      # aps
      rigaer78-ap1: 30

  - vid: 40
    role: dhcp
    prefix: 10.31.122.0/24
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      rigaer78-core: 1
