---

airmax_devices:
  - name: "schreiner-f2a"
    target: "10.31.97.98"
  - name: "schreiner-sama"
    target: "10.31.97.99"
  - name: "schreiner-client-1"
    target: "10.31.97.101"
  - name: "schreiner-client-2"
    target: "10.31.97.102"