---

location: rixbox
role: corerouter
model: ubnt_usw-flex

poemgr_power_budget: 24
poemgr_ports:
  # Port 2 is our uplink LiteBeam to RHNK
  - name: lan2
    port: 3
    disabled: 0
  # and the rest is APs
  - name: lan3
    port: 2
    disabled: 0
  - name: lan4
    port: 1
    disabled: 0
  - name: lan5
    port: 0
    disabled: 0
