---
ipv6_prefix: "2001:bf7:830:8e00::/56"

networks:
  - vid: 10
    role: mesh
    name: mesh_sama
    prefix: 10.31.79.67/32
    ipv6_subprefix: -1

  - vid: 42
    role: mgmt
    prefix: 10.31.81.80/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      rigaer83-core: 1
      rigaer83-sama: 2

  - vid: 40
    role: dhcp
    prefix: 10.31.91.192/26
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      rigaer83-core: 1
