---
ipv6_prefix: "2001:bf7:750:4a00::/56"

networks:
  - vid: 42
    role: mgmt
    prefix: 10.31.146.128/26
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      habersaath-core: 1
      habersaath-sw-a: 2
      habersaath-sw-b: 3
      habersaath-sw-c: 4
      habersaath-sw-d: 5
      habersaath-ap-a1: 10
      habersaath-ap-a2: 11
      habersaath-ap-a3: 12
      habersaath-ap-a4: 13
      habersaath-ap-a5: 14
      habersaath-ap-a6: 15
      habersaath-ap-b1: 20
      habersaath-ap-b2: 21
      habersaath-ap-b3: 22
      habersaath-ap-b4: 23
      habersaath-ap-b5: 24
      habersaath-ap-b6: 25
      habersaath-ap-c1: 30
      habersaath-ap-c2: 31
      habersaath-ap-c3: 32
      habersaath-ap-c4: 33
      habersaath-ap-c5: 34
      habersaath-ap-c6: 35
      habersaath-ap-d1: 40
      habersaath-ap-d2: 41
      habersaath-ap-d3: 42
      habersaath-ap-d4: 43
      habersaath-ap-d5: 44
      habersaath-ap-d6: 45

  - vid: 40
    role: dhcp
    prefix: 10.31.147.0/25
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      habersaath-core: 1

location__channel_assignments_11a_standard__to_merge:
      habersaath-ap-a1: 36-20
      habersaath-ap-a2: 40-20
      habersaath-ap-a3: 44-20
      habersaath-ap-a4: 48-20
      habersaath-ap-a5: 36-20
      habersaath-ap-a6: 40-20
      habersaath-ap-b1: 44-20
      habersaath-ap-b2: 48-20
      habersaath-ap-b3: 36-20
      habersaath-ap-b4: 40-20
      habersaath-ap-b5: 44-20
      habersaath-ap-b6: 48-20
      habersaath-ap-c1: 36-20
      habersaath-ap-c2: 40-20
      habersaath-ap-c3: 44-20
      habersaath-ap-c4: 48-20
      habersaath-ap-c5: 36-20
      habersaath-ap-c6: 40-20
      habersaath-ap-d1: 44-20
      habersaath-ap-d2: 48-20
      habersaath-ap-d3: 36-20
      habersaath-ap-d4: 40-20
      habersaath-ap-d5: 44-20
      habersaath-ap-d6: 48-20

location__channel_assignments_11g_standard__to_merge:
      habersaath-ap-a1: 1-20
      habersaath-ap-a2: 5-20
      habersaath-ap-a3: 9-20
      habersaath-ap-a4: 13-20
      habersaath-ap-a5: 1-20
      habersaath-ap-a6: 5-20
      habersaath-ap-b1: 9-20
      habersaath-ap-b2: 13-20
      habersaath-ap-b3: 1-20
      habersaath-ap-b4: 5-20
      habersaath-ap-b5: 9-20
      habersaath-ap-b6: 13-20
      habersaath-ap-c1: 1-20
      habersaath-ap-c2: 5-20
      habersaath-ap-c3: 9-20
      habersaath-ap-c4: 13-20
      habersaath-ap-c5: 1-20
      habersaath-ap-c6: 5-20
      habersaath-ap-d1: 9-20
      habersaath-ap-d2: 13-20
      habersaath-ap-d3: 1-20
      habersaath-ap-d4: 5-20
      habersaath-ap-d5: 9-20
      habersaath-ap-d6: 13-20
