---
ipv6_prefix: 2001:bf7:820:400::/56

# mgmt: 10.31.16.0/28
# mesh: 10.31.16.16/28
# dhcp: 10.31.16.64/26
# prdhcp: 10.31.174.128/26
networks:

  - vid: 20
    role: mesh
    name: mesh_core
    prefix: 10.31.16.16/32
    ipv6_subprefix: -1

  - vid: 40
    role: dhcp
    name: dhcp
    prefix: 10.31.16.64/26
    ipv6_subprefix: -2
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      kirchhof-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.16.0/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      kirchhof-core: 1
      kirchhof-switch: 2         # AirOS
      kirchhof-switch-keller: 3  # TP-Link
      kirchhof-nf-vorne: 4
      kirchhof-nf-hinten: 5
      kirchhof-n-nf-5ghz: 6
      kirchhof-w-nf-5ghz: 7

  - vid: 50
    role: ext
    name: vodafone
    tunnel_wan_ip: 192.168.0.4/24
    tunnel_wan_gw: 192.168.0.1
    tunnel_connections: 1
    tunnel_timeout: 600
    tunnel_mtu: 1400
    tunnel_mesh_prefix_ipv4: 10.31.16.17/32

location__channel_assignments_11a_standard__to_merge:
  kirchhof-n-nf-5ghz: 36-20
  kirchhof-w-nf-5ghz: 40-20
  kirchhof-nf-vorne: 44-20
  kirchhof-nf-hinten: 36-20

location__channel_assignments_11b_standard__to_merge:
  kirchhof-nf-vorne: 13-20
  kirchhof-nf-hinten: 9-20
