---

freifunk_global_prefix: 2001:bf7::/32
freifunk_wahlkreis_prefixes:
  - 2001:bf7:830::/44
  - 2001:bf7:860::/44

freifunk_wahlkreis_announcement_prefix: 44
# Change to 48 if you wnat to announce 48s

local_asn: 65002
peer_asn: 25291

role_uplink_gateway_sysctl__to_merge:
  net.netfilter.nf_conntrack_max: 524288

wireguard_port_start: 51820
wireguard_port_end: 52820
wireguard_wg_key: '/etc/wireguard/wg.key'
wireguard_wg_pub: '/etc/wireguard/wg.pub'


gre_metric: 64

# Inbound is filtered by default
inbound_allow:
  - name: 'k9-core SSH'
    dst: 2001:bf7:830:8d00::/128
    proto: tcp
    dst_port: 22

#  - name: Rule Description (mandatory)
#    dst: Destination IP (mandatory)
#    src: Source IP
#    proto: [tcp, udp, icmp.]
#    src_port:
#    dst_port: 22
